### ISSUE TITLE
Hi, is the code complete?

### ISSUE THREAD

**Issue by PallHaraldsson** [adubredu/PyBullet.jl#5]
Two things surprise me.

I took a look, and is the code really this short, and thus complete?

I found it at juliahub and it's <s>not registered yet</s>, so intrigued why it got there? It's no harm, I can still install, I just thought they waited for registration (but maybe not doing that is by design).

EDIT, I thought not registered, so so unclear and strange why:

```
(@v1.8) pkg> add PyBullet
ERROR: The following package names could not be resolved:
```

Maybe the URL should have PyBullet, not Pybullet for consistency, if easily renamed.

It's a little slower than I would like (not because of PythonCall?), does it need to build each time Julia is run like this? Not a problem I guess, I'm just curious in general about PythonCall.
```
julia> @time using PyBullet
pybullet build time: Jan 28 2022 20:17:22
  6.642588 seconds (7.07 M allocations: 383.775 MiB, 1.54% gc time, 83.61% compilation time: 0% of which was recompilation)

julia> @time using PyBullet
  0.594514 seconds (363.42 k allocations: 18.947 MiB, 10.58% gc time, 99.95% compilation time: 98% of which was recompilation)

julia> @time using PyBullet
  0.000112 seconds (109 allocations: 9.211 KiB)
```

**Comment by adubredu** [comment]
The code is complete.  Since this package is mainly just a lightweight Julia wrapper for the PyBullet python package, it is naturally short and compact.  

This package finally appeared in the Julia registry yesterday so it should be fully registered now. So you should be able to install it using

```
add PyBullet
```

Just like with any Julia package,  first time package loading takes a bit of time.  After the first few calls,  it gets much faster.

**Comment by PallHaraldsson** [comment]
>Just like with any Julia package, first time package loading takes a bit of time.

It doesn't get faster for me, next using keeping:
```
julia> @time using PyBullet
pybullet build time: Jan 28 2022 20:17:22
```

which is unusual to see. I tried addint to your package (copied from Plots.jl), but it was ineffective:
```
if isdefined(Base, :Experimental) && isdefined(Base.Experimental, Symbol("@optlevel"))
    @eval Base.Experimental.@optlevel 1
end
#if isdefined(Base, :Experimental) && isdefined(Base.Experimental, Symbol("@max_methods"))
#    @eval Base.Experimental.@max_methods 1
#end
```

The non-commented code has been used for 3 year, so at least "Experimental" there not something to worry about. I Tried wit or without the commented code, it didn't matter. [It's not commented at Plots.jl, but I see it's a more recent addition, so I wanted to check what it does.]
